<?php
/**
 * Installer: German texts (English text => German text).
 *
 * Copyright (C) 2026 Christoph Scheel <https://chrisscheel.de>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
return [
    'Already installed' => 'Bereits installiert',
    'Could not write core/config.php.' => 'core/config.php konnte nicht geschrieben werden.',
    'Database' => 'Datenbank',
    'Database error: {1}' => 'Datenbankfehler: {1}',
    'Database name' => 'Datenbankname',
    'Delete the {1} folder from your webspace now. It refuses to run again anyway, but there is no reason to keep it online.' => 'Lösche jetzt den Ordner {1} von deinem Webspace. Er verweigert zwar eine zweite Installation, gehört aber nicht auf einen Live-Server.',
    'Dial in' => 'Anwählen',
    'Everything is set up. Log in to the terminal with your sysop handle, or open the backend to fill in imprint and privacy policy before you tell anyone about your box.' => 'Alles ist eingerichtet. Logg dich im Terminal mit deinem Sysop-Handle ein oder trag im Backend Impressum und Datenschutzerklärung ein, bevor du die Box bekannt machst.',
    'Host' => 'Host',
    'Install' => 'Installieren',
    'Language' => 'Sprache',
    'Language of the BBS' => 'Sprache der Mailbox',
    'Location' => 'Standort',
    'MySQL or MariaDB' => 'MySQL oder MariaDB',
    'Name of the BBS' => 'Name der Mailbox',
    'Open the BBS' => 'Mailbox öffnen',
    'PDO extension' => 'PDO-Erweiterung',
    'PDO SQLite or PDO MySQL' => 'PDO SQLite oder PDO MySQL',
    'PHP 8.1 or newer' => 'PHP 8.1 oder neuer',
    'Password' => 'Passwort',
    'Password (at least 8 characters)' => 'Passwort (mindestens 8 Zeichen)',
    'Please enter a name for your BBS.' => 'Bitte gib einen Namen für deine Mailbox ein.',
    'Port (empty = default)' => 'Port (leer = Standard)',
    'Repeat password' => 'Passwort wiederholen',
    'Requirement missing: {1}' => 'Voraussetzung fehlt: {1}',
    'SQLite (one file in data/, nothing to configure)' => 'SQLite (eine Datei in data/, keine Einrichtung nötig)',
    'Server check' => 'Serverprüfung',
    'Set up your BBS' => 'Mailbox einrichten',
    'Setup {1}' => 'Einrichtung {1}',
    'Source code' => 'Quellcode',
    'Sysop account' => 'Sysop-Account',
    'Sysop backend' => 'Sysop-Backend',
    'Sysop handle' => 'Sysop-Handle',
    'Sysop handle: 3 to 20 letters, digits, spaces, dots, dashes or underscores.' => 'Sysop-Handle: 3 bis 20 Buchstaben, Ziffern, Leerzeichen, Punkte, Binde- oder Unterstriche.',
    'Table prefix' => 'Tabellenpräfix',
    'The passwords do not match.' => 'Die Passwörter stimmen nicht überein.',
    'The sysop password needs at least 8 characters.' => 'Das Sysop-Passwort braucht mindestens 8 Zeichen.',
    'There are already WebCarrier BBS tables with this prefix in the database.' => 'In der Datenbank gibt es schon Tabellen von WebCarrier BBS mit diesem Präfix.',
    'This BBS is already set up. To install again, delete {1} first. You can delete the {2} folder now.' => 'Diese Mailbox ist bereits eingerichtet. Für eine Neuinstallation zuerst {1} löschen. Den Ordner {2} kannst du jetzt löschen.',
    'User' => 'Benutzer',
    'WebCarrier BBS setup' => 'WebCarrier BBS einrichten',
    'Your BBS is online' => 'Deine Mailbox ist online',
    'Your box' => 'Deine Box',
    'ZipArchive (optional, reads FILE_ID.DIZ)' => 'ZipArchive (optional, liest FILE_ID.DIZ)',
    'core/ writable' => 'core/ beschreibbar',
    'data/ writable' => 'data/ beschreibbar',
    'mbstring extension' => 'mbstring-Erweiterung',
];
